"""align order column names

Revision ID: a0401b414c4e
Revises: 88931acdb5f7
Create Date: 2026-09-24 07:46:05.986894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0401b414c4e'
down_revision: Union[str, Sequence[str], None] = '88931acdb5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('waiter_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_orders_wait_id'), table_name='orders')
    op.create_index(op.f('ix_orders_waiter_id'), 'orders', ['waiter_id'], unique=False)
    op.drop_constraint(op.f('orders_wait_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['waiter_id'], ['id'])
    op.drop_column('orders', 'create_at')
    op.drop_column('orders', 'wait_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('wait_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_wait_id_fkey'), 'orders', 'users', ['wait_id'], ['id'])
    op.drop_index(op.f('ix_orders_waiter_id'), table_name='orders')
    op.create_index(op.f('ix_orders_wait_id'), 'orders', ['wait_id'], unique=False)
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'waiter_id')
    # ### end Alembic commands ###
