"""add reservation composite index

Revision ID: c7250f75f00f
Revises: 276039cd5eb9
Create Date: 2026-09-27 18:57:33.638254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7250f75f00f'
down_revision: Union[str, Sequence[str], None] = '276039cd5eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reservations_table_start_end', 'reservations', ['table_id', 'start_at', 'end_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reservations_table_start_end', table_name='reservations')
    # ### end Alembic commands ###
