"""align order placement timestamp and index

Revision ID: cc22bd716b84
Revises: c7250f75f00f
Create Date: 2026-09-27 19:10:47.962092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc22bd716b84'
down_revision: Union[str, Sequence[str], None] = 'c7250f75f00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "orders",
        sa.Column("placed_at", sa.DateTime(), nullable=True),
    )

    op.execute(
        sa.text(
            "UPDATE orders SET placed_at = created_at "
            "WHERE placed_at IS NULL"
        )
    )

    op.alter_column(
        "orders",
        "placed_at",
        nullable=False,
    )

    op.create_index(
        "ix_orders_status_placed_at",
        "orders",
        ["status", "placed_at"],
        unique=False,
    )

    op.drop_column("orders", "created_at")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index('ix_orders_status_placed_at', table_name='orders')
    op.drop_column('orders', 'placed_at')
    # ### end Alembic commands ###
